In [ ]:
import torch
from torch import nn

In [ ]:
def corr2d(X, K):
  h, w = K.shape
  Y= torch.zeros((X.shape[0] - h+1,X.shape[1]- w + 1))
  print("shape of the input -", X.shape)
  print("shape of the kernel -", K.shape)
  print("shape of the output -", Y.shape)
  for i in range(Y.shape[0]):
    for j in range(Y.shape[1]):
      Y[i, j] = (X[i:i+h, j:j+w]*K).sum()
  return Y

In [ ]:
X=torch.tensor([[0.0,1.0,2.0],[3.0,4.0,5.0],[6.0,7.0,8.0]])
K=torch.tensor([[0.0,1.0],[2.0,3.0]])
print(corr2d(X,K))

shape of the input - torch.Size([3, 3])
shape of the kernel - torch.Size([2, 2])
shape of the output - torch.Size([2, 2])
tensor([[19., 25.],
        [37., 43.]])


In [ ]:
X=torch.ones((6,8), dtype = torch.float32)
X[:,2:6]=0
X

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]])

In [ ]:
K= torch.tensor([[1,-1]], dtype=torch.float32)
K

tensor([[ 1., -1.]])

In [ ]:
Y= corr2d(X,K)
Y

shape of the input - torch.Size([6, 8])
shape of the kernel - torch.Size([1, 2])
shape of the output - torch.Size([6, 7])


tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.]])

In [ ]:
corr2d(X.t(),K)

shape of the input - torch.Size([8, 6])
shape of the kernel - torch.Size([1, 2])
shape of the output - torch.Size([8, 5])


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

Learning a Kernel

In [ ]:
conv2d = nn.LazyConv2d(1, kernel_size=(1,2), bias=False)
X=X.reshape([1,1,6,8])
Y=Y.reshape([1,1,6,7])
lr=3e-2
print(X)
print(Y)
print(lr)
for i in range(10):
  Y_hat=conv2d(X)
  l=(Y_hat-Y)**2
  conv2d.zero_grad()
  l.sum().backward()
  conv2d.weight.data[:] -= lr * conv2d.weight.grad
  if (i+1)%2==0:
    print(f'Epoch {i+1}, loss {l.sum():.3f}')


tensor([[[[1., 1., 0., 0., 0., 0., 1., 1.],
          [1., 1., 0., 0., 0., 0., 1., 1.],
          [1., 1., 0., 0., 0., 0., 1., 1.],
          [1., 1., 0., 0., 0., 0., 1., 1.],
          [1., 1., 0., 0., 0., 0., 1., 1.],
          [1., 1., 0., 0., 0., 0., 1., 1.]]]])
tensor([[[[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
          [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
          [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
          [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
          [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
          [ 0.,  1.,  0.,  0.,  0., -1.,  0.]]]])
0.03
Epoch 2, loss 1.440
Epoch 4, loss 0.361
Epoch 6, loss 0.109
Epoch 8, loss 0.038
Epoch 10, loss 0.015


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [ ]:
conv2d.weight.data.reshape((1,2))

tensor([[ 0.9828, -1.0071]])

Pooling operation (Max amd average pooling

In [ ]:
def pool2d(X, pool_size, mode='max'):
  p_h, p_w = pool_size
  Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
  for i in range(Y.shape[0]):
    for j in range(Y.shape[1]):
      if mode == 'max':
        Y[i, j] = X[i: i + p_h, j: j + p_w].max()
      elif mode == 'avg':
        Y[i, j] = X[i: i + p_h, j: j + p_w].mean()
  return Y

In [ ]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

In [ ]:
pool2d(X, (2, 2), 'avg')

tensor([[2., 3.],
        [5., 6.]])