In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.model_selection  import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score

from sklearn import preprocessing
from sklearn.preprocessing import RobustScaler
from sklearn.metrics import mean_squared_error

import pickle
from google.colab import files

In [ ]:
uploaded = files.upload()

Saving Fertilizer Prediction (2).csv to Fertilizer Prediction (2) (2).csv


In [ ]:
data = pd.read_csv('Fertilizer Prediction (2).csv')
data

Temparature  Humidity   Moisture Soil Type  Crop Type  Nitrogen  \
0            26         52        38     Sandy      Maize        37   
1            29         52        45     Loamy  Sugarcane        12   
2            34         65        62     Black     Cotton         7   
3            32         62        34       Red    Tobacco        22   
4            28         54        46    Clayey      Paddy        35   
..          ...        ...       ...       ...        ...       ...   
94           25         50        32    Clayey     Pulses        24   
95           30         60        27       Red    Tobacco         4   
96           38         72        51     Loamy      Wheat        39   
97           36         60        43     Sandy    Millets        15   
98           29         58        57     Black  Sugarcane        12   

    Potassium  Phosphorous Fertilizer Name  
0           0            0            Urea  
1           0           36             DAP  
2           9           30        14-35-14  
3           0           20           28-28  
4           0            0            Urea  
..        ...          ...             ...  
94          0           19           28-28  
95         17           17        10-26-26  
96          0            0            Urea  
97          0           41             DAP  
98          0           10           20-20  

[99 rows x 9 columns]

In [ ]:
le = LabelEncoder()
data['Soil Type'] = le.fit_transform(data['Soil Type'])
data['Crop Type'] = le.fit_transform(data['Crop Type'])
data['Fertilizer Name'] = le.fit_transform(data['Fertilizer Name'])
data

Temparature  Humidity   Moisture  Soil Type  Crop Type  Nitrogen  \
0            26         52        38          4          3        37   
1            29         52        45          2          8        12   
2            34         65        62          0          1         7   
3            32         62        34          3          9        22   
4            28         54        46          1          6        35   
..          ...        ...       ...        ...        ...       ...   
94           25         50        32          1          7        24   
95           30         60        27          3          9         4   
96           38         72        51          2         10        39   
97           36         60        43          4          4        15   
98           29         58        57          0          8        12   

    Potassium  Phosphorous  Fertilizer Name  
0           0            0                6  
1           0           36                5  
2           9           30                1  
3           0           20                4  
4           0            0                6  
..        ...          ...              ...  
94          0           19                4  
95         17           17                0  
96          0            0                6  
97          0           41                5  
98          0           10                3  

[99 rows x 9 columns]

In [ ]:
x = data.drop('Fertilizer Name', axis=1).copy()
y = data['Fertilizer Name'].copy()
print(x, y)

    Temparature  Humidity   Moisture  Soil Type  Crop Type  Nitrogen  \
0            26         52        38          4          3        37   
1            29         52        45          2          8        12   
2            34         65        62          0          1         7   
3            32         62        34          3          9        22   
4            28         54        46          1          6        35   
..          ...        ...       ...        ...        ...       ...   
94           25         50        32          1          7        24   
95           30         60        27          3          9         4   
96           38         72        51          2         10        39   
97           36         60        43          4          4        15   
98           29         58        57          0          8        12   

    Potassium  Phosphorous  
0           0            0  
1           0           36  
2           9           30  
3           0      

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.2, shuffle=True, random_state=1)
scaler = RobustScaler()
scaler.fit(x_train)
train_x=scaler.transform(x_train)

In [ ]:
logreg=LogisticRegression()
logreg.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
# Pair the feature name with the coefficient
list(zip(data, logreg.coef_))

[('Temparature',
  array([-0.07866436,  0.04327691, -0.02602915, -0.16887631,  0.17386186,
         -0.27199146,  0.31940821,  0.21909347])),
 ('Humidity ',
  array([ 0.02473202,  0.06127621, -0.04417832,  0.09849955, -0.21369075,
          0.05080333,  0.41286823, -0.18176037])),
 ('Moisture',
  array([ 0.01851295,  0.06480655,  0.11797524,  0.02899572, -0.02037931,
         -0.23582447, -0.16964164, -0.25182533])),
 ('Soil Type',
  array([-0.02458491, -0.03044134, -0.01938997,  0.07433155,  0.08878041,
          0.24579412, -0.15820868,  0.10315255])),
 ('Crop Type',
  array([ 0.0701414 , -0.12780542, -0.01883319,  0.00065415, -0.02297469,
         -0.14640389, -0.39022378,  0.46557118])),
 ('Nitrogen',
  array([-0.01013709, -0.01111291, -0.00954462, -0.03360466, -0.00559753,
          0.35762236, -0.01420235, -0.3542315 ]))]

In [ ]:
y_pred = logreg.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy*100)

Accuracy: 86.25


In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 0  5  2  0  0  0  0]
 [ 0 12  0  0  0  0  0]
 [ 0  2  3  0  0  0  0]
 [ 0  0  0 10  2  0  0]
 [ 0  0  0  0 13  0  0]
 [ 0  0  0  0  0 14  0]
 [ 0  0  0  0  0  0 17]]


In [ ]:
pickle.dump(logreg, open('21bai1499_lab_6_logreg.pkl', 'wb'))

In [ ]:
def get_user_input():
    temperature = float(input("Temperature (in degrees Celsius): "))
    humidity = float(input("Humidity (in percentage): "))
    moisture = float(input("Moisture (ratio of water mass): "))
    soil_type = le.transform([input("Soil Type: ")])[0]
    crop_type = le.transform([input("Crop Type: ")])[0]
    nitrogen = float(input("Nitrogen content (in percentage): "))
    potassium = float(input("Potassium content (in percentage): "))
    phosphorous = float(input("Phosphorous content (in percentage): "))

    user_input = [temperature, humidity, moisture, soil_type, crop_type, nitrogen, potassium, phosphorous]
    return user_input

def preprocess_input(user_input):
    user_input = scaler.transform([user_input])
    return user_input

user_input = get_user_input()
user_input = preprocess_input(user_input)

loaded_model = pickle.load(open('fertilizer_model_knn.pkl', 'rb'))
prediction = loaded_model.predict(user_input)

print('Recommended fertilizer:', prediction)


# New Section